# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160709_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
