# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20160709_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
