# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_connectuser_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('teacher_id', models.BigIntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('course_info', models.TextField(max_length=500)),
                ('jwb_credit', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.BigIntegerField()),
                ('teacher_id', models.BigIntegerField()),
                ('student_id', models.BigIntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('order_info', models.CharField(max_length=200)),
                ('order_state', models.CharField(max_length=50)),
            ],
        ),
    ]
