# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20160711_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 16, 29, 33, 85816)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 16, 29, 33, 86821)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 16, 29, 33, 84816)),
        ),
    ]
