# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20160711_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 10, 45, 49, 805930)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 10, 45, 49, 805930)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 10, 45, 49, 804930)),
        ),
    ]
