# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20160712_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
