# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20160712_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='info',
            field=models.CharField(default='勤奋刻苦，品学兼优，力争上游', max_length=200),
        ),
    ]
