# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_userinfo_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=50)),
            ],
        ),
    ]
